---

volumes:
  psql-data:

services:
  # Jupyter Lab - Prototyping
  jupyter:
    env_file:
      - .env
    container_name: jupyter
    build:
      context: .
      dockerfile: Dockerfile.jupyter
      args:
        JUPYTER_BASE_URL:
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 8890:8888
    restart: always

  # FastAPI server that operates the chat component.
  fastapi:
    env_file:
      - .env
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./:/code
    ports:
      - 8080:8080
    restart: always

  # Postgres database for storing chat data.
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - psql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  default:
    name: app-network
